/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'champagne-gold': '#D4AF37',
        error: '#ba1a1a',
        'surface-variant': '#e0e3e5',
        'on-surface': '#191c1e',
        'slate-border': '#E2E8F0',
        background: '#f7f9fb',
        'charcoal-surface': '#1E293B',
        'on-surface-variant': '#45464d',
        'champagne-light': '#F4EFEA',
        outline: '#76777d',
        'outline-variant': '#c6c6cd',
        primary: '#000000',
        'surface-container-low': '#f2f4f6',
        'on-secondary': '#ffffff',
        surface: '#f7f9fb',
        'surface-container': '#eceef0',
        'on-tertiary': '#ffffff',
        'on-background': '#191c1e',
        'deep-obsidian': '#0A0F1D',
        'inverse-surface': '#2d3133',
        'surface-bright': '#f7f9fb',
        secondary: '#725b38',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        margin: '4rem',
        'space-xs': '0.25rem',
        'space-xl': '2.5rem',
        'space-3xl': '6rem',
        gutter: '1.5rem',
        'margin-tablet': '2rem',
        'gutter-mobile': '1rem',
        'margin-mobile': '1.25rem',
        'space-md': '1rem',
        'space-2xl': '4rem',
        'space-sm': '0.5rem',
        'space-lg': '1.5rem',
      },
      fontFamily: {
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'price-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'display-hero-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'title-editorial': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-hero': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-md': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'price-lg': ['20px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-hero-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '300' }],
        'title-editorial': ['18px', { lineHeight: '26px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '300' }],
      },
    },
  },
  plugins: [],
};
